recipe: default.v1
language: en
assistant_id: se-take-home-test-2026H1

pipeline:
- name: WhitespaceTokenizer

- name: CountVectorsFeaturizer

- name: DIETClassifier
  epochs: 100
  constrain_similarities: true

- name: RegexEntityExtractor
  use_regexes: true
  use_lookup_tables: true
  use_word_boundaries: true
  
- name: NLUCommandAdapter

- name: SearchReadyLLMCommandGenerator
  llm:
    model_group: gpt-4o
  flow_retrieval:
    active: false
    
policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  vector_store:
    type: "faiss"
    source: "./docs"
  llm:
    model_group: gpt-4o
